name: Deploy backend

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'  # Adjust based on your project

    - name: Build with Maven
      run: mvn clean package -DskipTests=false

    - name: Deploy to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "target/*.jar"
        target: "/home/${{ secrets.EC2_USER }}/app"

    - name: SSH and Run App
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          bash /home/ec2-user/app/deploy.sh
          
    - name: SSH and Restart App with Supervisor
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          pgrep supervisord > /dev/null || supervisord -c /home/ec2-user/supervisord.conf          
          sudo supervisorctl reread
          sudo supervisorctl update
          sudo supervisorctl restart springapp || sudo supervisorctl start springapp
